name: Sync OAS to ReadMe

on:
  push:
    branches:
      - main

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Upload Autosuggest API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/autosuggest.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.AUTOSUGGEST_ID }}

      - name: Upload Bestseller API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/bestseller.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.BESTSELLER_ID }}

      - name: Upload Content Search API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/content-search.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.CONTENT_SEARCH_ID }}

      - name: Upload Recommendations & Pathways API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/recommendations-pathways.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.RECS_PATHWAYS_ID }}

      - name: Upload Search & Category API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/search-category.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.SEARCH_CATEGORY_ID }}

      - name: Upload Email Widget API to Readme
        uses: readmeio/rdme@v8
        with:
          rdme:
            openapi discovery/email-spec.yaml --key=${{ secrets.API_KEY_DISCOVERY }} --id=${{ secrets.EMAIL_RECS_ID }}
